### PR TITLE
wide open regex

### PR DESCRIPTION
**Pull request by rizen**
I got rid of the or on line 114, because otherwise every command gets processed with or without the prefix

### CODE REVIEW

**Comment by topaz** [comment]
This regex exists to create commands that exactly match a specific string of text.  Its cost is negligible; each message is checked for whether it exists in a hash, nothing more.

**Comment by rizen** [comment]
Sorry I din't make myself clear. The regex the way it is now matches both:

commands

AND

!commands

I don't think that's what you intended.

**Comment by topaz** [comment]
You know what, you're absolutely right; to do what I just said in a sane way, it would need to be a separate type of command matched against a separate list.  Not sure what I was thinking, nor why this branch is here.

**Comment by rizen** [comment]
For the record, I'm all for that second list! I can see the need to be able to match on arbitrary things like whether or not someone mentions the bot by name for example.

**Pull request merged**
